port: /dev/serial/by-id/usb-ROBOTIS_OpenRB-150_E5A430E050304A46462E3120FF121405-if00
baud: 1000000
motors:
  pan:
    id: 1
    min_deg: -180.0
    max_deg: 0.0
    inverted: false
  tilt:
    id: 2
    min_deg: 135
    max_deg: 325.0
    inverted: false
